version: "3.9"
services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: "MoneyTracker"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345678"
            LANG: ru_RU.UTF-8
            LANGUAGE: ru_RU.UTF-8
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgres
volumes:
    postgres: { }     